name: theme_changer_with_mobx_and_hive
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.2
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
